source 'https://github.com/CocoaPods/Specs.git'
project "UncommonCrypto.xcodeproj"
use_frameworks!

target 'UncommonCrypto_Example' do
#  pod 'UncommonCrypto', :git => '../'
 pod 'UncommonCrypto', :path => '../'

  target 'UncommonCrypto_Tests' do
    inherit! :search_paths

    pod 'Nimble'
  end
end
