use_frameworks!

target 'UncommonCryptoPlayground' do
pod 'UncommonCrypto', :path => '/Users/dan/Documents/Projects/UncommonCrypto'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
